# Generated by Django 4.2.7 on 2023-12-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('crm', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('especialidade', models.CharField(max_length=50)),
            ],
        ),
    ]
